import '../models/exercise.dart';

/// Base de données complète de 100+ exercices
class ComprehensiveExerciseDatabase {
  static List<Exercise> getAllExercises() {
    return [
      // ============ PECTORAUX (15 exercices) ============
      Exercise(
        id: 'bench_press',
        name: 'Développé Couché Barre',
        description: 'Exercice de base pour les pectoraux, développe la force et la masse.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: ['Triceps', 'Épaules'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Allongez-vous sur le banc, pieds au sol',
          'Saisissez la barre largeur épaules',
          'Descendez vers la poitrine',
          'Poussez explosif vers le haut',
        ],
      ),
      Exercise(
        id: 'incline_bench_press',
        name: 'Développé Incliné',
        description: 'Cible le haut des pectoraux.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: ['Triceps', 'Épaules'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Banc incliné à 30-45 degrés',
          'Saisissez la barre',
          'Descendez vers le haut de la poitrine',
          'Poussez vers le haut',
        ],
      ),
      Exercise(
        id: 'decline_bench_press',
        name: 'Développé Décliné',
        description: 'Cible le bas des pectoraux.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: ['Triceps'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Banc décliné, pieds fixés',
          'Saisissez la barre',
          'Descendez vers le bas de la poitrine',
          'Poussez vers le haut',
        ],
      ),
      Exercise(
        id: 'dumbbell_press',
        name: 'Développé Haltères',
        description: 'Permet une plus grande amplitude de mouvement.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: ['Triceps', 'Épaules'],
        equipment: 'Haltères',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Allongé sur banc, haltères en main',
          'Coudes à 90 degrés',
          'Poussez vers le haut',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'dumbbell_flyes',
        name: 'Écartés Haltères',
        description: 'Étirement profond des pectoraux.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: [],
        equipment: 'Haltères',
        difficulty: 'Intermédiaire',
        category: 'Isolation',
        instructions: [
          'Allongé sur banc, haltères au-dessus',
          'Écartez les bras sur les côtés',
          'Coudes légèrement fléchis',
          'Ramenez en position haute',
        ],
      ),
      Exercise(
        id: 'push_up',
        name: 'Pompes',
        description: 'Exercice au poids du corps classique.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: ['Triceps', 'Épaules', 'Abdominaux'],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Position de planche',
          'Mains sous les épaules',
          'Descendez en fléchissant les coudes',
          'Poussez pour remonter',
        ],
      ),
      Exercise(
        id: 'diamond_push_up',
        name: 'Pompes Diamant',
        description: 'Variante ciblant davantage les triceps.',
        primaryMuscles: ['Triceps'],
        secondaryMuscles: ['Pectoraux'],
        equipment: 'Poids du corps',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'Position pompe, mains rapprochées',
          'Formez un diamant avec les pouces et index',
          'Descendez en gardant les coudes près du corps',
          'Poussez pour remonter',
        ],
      ),
      Exercise(
        id: 'cable_crossover',
        name: 'Écarté Poulie Vis-à-Vis',
        description: 'Tension continue sur les pectoraux.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Intermédiaire',
        category: 'Isolation',
        instructions: [
          'Debout entre deux poulies hautes',
          'Saisissez les poignées',
          'Ramenez les mains devant vous',
          'Revenez contrôlé',
        ],
      ),
      Exercise(
        id: 'chest_dips',
        name: 'Dips Pectoraux',
        description: 'Excellent pour le bas des pectoraux.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: ['Triceps', 'Épaules'],
        equipment: 'Barres parallèles',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'Saisissez les barres',
          'Penchez le buste en avant',
          'Descendez en fléchissant les coudes',
          'Poussez pour remonter',
        ],
      ),
      Exercise(
        id: 'pec_deck',
        name: 'Pec Deck',
        description: 'Machine pour isolation des pectoraux.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Assis sur la machine',
          'Coudes sur les coussins',
          'Ramenez les coudes devant vous',
          'Revenez lentement',
        ],
      ),
      Exercise(
        id: 'svend_press',
        name: 'Svend Press',
        description: 'Compression isométrique des pectoraux.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: ['Épaules'],
        equipment: 'Haltères',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Debout, deux disques ou haltères devant la poitrine',
          'Pressez les mains ensemble',
          'Poussez devant vous',
          'Ramenez vers la poitrine',
        ],
      ),
      Exercise(
        id: 'landmine_press',
        name: 'Développé Landmine',
        description: 'Variante unilatérale pour les pectoraux.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: ['Épaules', 'Triceps'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Barre calée dans un angle',
          'Saisissez l extrémité',
          'Poussez devant vous',
          'Alternez les bras',
        ],
      ),
      Exercise(
        id: 'wide_push_up',
        name: 'Pompes Larges',
        description: 'Variante ciblant plus les pectoraux.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: ['Triceps', 'Épaules'],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Position pompe, mains plus larges',
          'Descendez en gardant le corps droit',
          'Poussez pour remonter',
          'Contractez les pectoraux en haut',
        ],
      ),
      Exercise(
        id: 'incline_dumbbell_press',
        name: 'Développé Incliné Haltères',
        description: 'Cible le haut des pectoraux avec haltères.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: ['Épaules', 'Triceps'],
        equipment: 'Haltères',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Banc incliné 30-45 degrés',
          'Haltères en main',
          'Poussez vers le haut',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'guillotine_press',
        name: 'Développé Guillotine',
        description: 'Variante du développé couché pour étirer les pectoraux.',
        primaryMuscles: ['Pectoraux'],
        secondaryMuscles: ['Épaules'],
        equipment: 'Barre',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'Allongé sur banc',
          'Descendez la barre vers le cou/haut de la poitrine',
          'Coudes écartés',
          'Poussez vers le haut',
        ],
      ),

      // ============ DOS (15 exercices) ============
      Exercise(
        id: 'pull_up',
        name: 'Tractions',
        description: 'Exercice roi pour le dos.',
        primaryMuscles: ['Grand dorsal'],
        secondaryMuscles: ['Biceps', 'Trapèzes'],
        equipment: 'Barre de traction',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'Saisissez la barre, paumes vers l avant',
          'Tirez jusqu à ce que le menton dépasse la barre',
          'Descendez contrôlé',
          'Répétez',
        ],
      ),
      Exercise(
        id: 'chin_up',
        name: 'Tractions Supination',
        description: 'Variante avec paumes vers soi, sollicite plus les biceps.',
        primaryMuscles: ['Grand dorsal', 'Biceps'],
        secondaryMuscles: ['Trapèzes'],
        equipment: 'Barre de traction',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'Saisissez la barre, paumes vers vous',
          'Tirez jusqu à ce que le menton dépasse',
          'Descendez lentement',
          'Répétez',
        ],
      ),
      Exercise(
        id: 'barbell_row',
        name: 'Rowing Barre',
        description: 'Exercice de base pour l épaisseur du dos.',
        primaryMuscles: ['Grand dorsal', 'Trapèzes'],
        secondaryMuscles: ['Biceps', 'Lombaires'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Buste penché à 45 degrés',
          'Saisissez la barre',
          'Tirez vers le bas de la poitrine',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'dumbbell_row',
        name: 'Rowing Haltère',
        description: 'Travail unilatéral du dos.',
        primaryMuscles: ['Grand dorsal'],
        secondaryMuscles: ['Biceps', 'Trapèzes'],
        equipment: 'Haltères',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Appuyé sur un banc',
          'Haltère dans une main',
          'Tirez le coude vers le haut',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'lat_pulldown',
        name: 'Tirage Vertical',
        description: 'Alternative aux tractions sur machine.',
        primaryMuscles: ['Grand dorsal'],
        secondaryMuscles: ['Biceps', 'Trapèzes'],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Assis sur la machine',
          'Saisissez la barre large',
          'Tirez vers le haut de la poitrine',
          'Revenez contrôlé',
        ],
      ),
      Exercise(
        id: 'seated_cable_row',
        name: 'Rowing Câble Assis',
        description: 'Tirage horizontal pour le milieu du dos.',
        primaryMuscles: ['Grand dorsal', 'Trapèzes'],
        secondaryMuscles: ['Biceps'],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Assis, pieds contre les cale-pieds',
          'Saisissez la poignée',
          'Tirez vers l abdomen',
          'Revenez en étirant',
        ],
      ),
      Exercise(
        id: 'deadlift',
        name: 'Soulevé de Terre',
        description: 'Exercice complet pour tout le corps.',
        primaryMuscles: ['Lombaires', 'Fessiers', 'Ischio-jambiers'],
        secondaryMuscles: ['Grand dorsal', 'Trapèzes', 'Quadriceps'],
        equipment: 'Barre',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'Barre au sol, pieds largeur hanches',
          'Saisissez la barre',
          'Soulevez en gardant le dos droit',
          'Verrouillez en haut',
          'Redescendez contrôlé',
        ],
      ),
      Exercise(
        id: 't_bar_row',
        name: 'Rowing T-Bar',
        description: 'Excellente pour l épaisseur du dos.',
        primaryMuscles: ['Grand dorsal', 'Trapèzes'],
        secondaryMuscles: ['Biceps'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Barre calée, chargée d un côté',
          'Saisissez la poignée',
          'Tirez vers la poitrine',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'face_pull',
        name: 'Face Pull',
        description: 'Excellent pour les trapèzes et l arrière d épaules.',
        primaryMuscles: ['Trapèzes', 'Épaules arrière'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Poulie haute avec corde',
          'Tirez vers le visage',
          'Écartez les mains',
          'Revenez contrôlé',
        ],
      ),
      Exercise(
        id: 'wide_grip_pulldown',
        name: 'Tirage Large Devant',
        description: 'Cible la largeur du dos.',
        primaryMuscles: ['Grand dorsal'],
        secondaryMuscles: ['Biceps'],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Prise large sur la barre',
          'Tirez vers le haut de la poitrine',
          'Penchez légèrement en arrière',
          'Revenez contrôlé',
        ],
      ),
      Exercise(
        id: 'inverted_row',
        name: 'Tirage Horizontal',
        description: 'Au poids du corps, excellent pour débutants.',
        primaryMuscles: ['Grand dorsal', 'Trapèzes'],
        secondaryMuscles: ['Biceps'],
        equipment: 'Barre',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Sous une barre fixe',
          'Corps droit, talons au sol',
          'Tirez la poitrine vers la barre',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'shrug',
        name: 'Shrug (Haussements d épaules)',
        description: 'Isolation des trapèzes supérieurs.',
        primaryMuscles: ['Trapèzes'],
        secondaryMuscles: [],
        equipment: 'Haltères',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Haltères dans chaque main',
          'Haussez les épaules vers le haut',
          'Contractez en haut',
          'Descendez lentement',
        ],
      ),
      Exercise(
        id: 'pendlay_row',
        name: 'Rowing Pendlay',
        description: 'Variante explosive du rowing barre.',
        primaryMuscles: ['Grand dorsal', 'Trapèzes'],
        secondaryMuscles: ['Biceps'],
        equipment: 'Barre',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'Barre au sol entre chaque rep',
          'Buste parallèle au sol',
          'Tirez explosif vers la poitrine',
          'Reposez au sol',
        ],
      ),
      Exercise(
        id: 'rack_pull',
        name: 'Rack Pull',
        description: 'Variante du soulevé de terre, focus haut du dos.',
        primaryMuscles: ['Trapèzes', 'Lombaires'],
        secondaryMuscles: ['Grand dorsal'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Barre positionnée à hauteur genoux',
          'Saisissez la barre',
          'Soulevez jusqu à extension complète',
          'Redescendez sur les supports',
        ],
      ),
      Exercise(
        id: 'machine_row',
        name: 'Rowing Machine',
        description: 'Machine guidée pour le dos.',
        primaryMuscles: ['Grand dorsal', 'Trapèzes'],
        secondaryMuscles: ['Biceps'],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Assis sur la machine',
          'Saisissez les poignées',
          'Tirez vers l abdomen',
          'Revenez contrôlé',
        ],
      ),

      // ============ ÉPAULES (12 exercices) ============
      Exercise(
        id: 'overhead_press',
        name: 'Développé Militaire',
        description: 'Exercice de base pour les épaules.',
        primaryMuscles: ['Épaules'],
        secondaryMuscles: ['Triceps', 'Trapèzes'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Debout, barre sur les épaules',
          'Poussez au-dessus de la tête',
          'Verrouillez en haut',
          'Redescendez contrôlé',
        ],
      ),
      Exercise(
        id: 'dumbbell_shoulder_press',
        name: 'Développé Épaules Haltères',
        description: 'Permet une amplitude naturelle.',
        primaryMuscles: ['Épaules'],
        secondaryMuscles: ['Triceps'],
        equipment: 'Haltères',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Assis ou debout, haltères aux épaules',
          'Poussez au-dessus de la tête',
          'Ramenez contrôlé',
          'Répétez',
        ],
      ),
      Exercise(
        id: 'lateral_raise',
        name: 'Élévations Latérales',
        description: 'Isolation des deltoïdes latéraux.',
        primaryMuscles: ['Épaules'],
        secondaryMuscles: [],
        equipment: 'Haltères',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Debout, haltères le long du corps',
          'Levez les bras sur les côtés',
          'Montez jusqu à hauteur épaules',
          'Descendez lentement',
        ],
      ),
      Exercise(
        id: 'front_raise',
        name: 'Élévations Frontales',
        description: 'Cible l avant des épaules.',
        primaryMuscles: ['Épaules'],
        secondaryMuscles: [],
        equipment: 'Haltères',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Debout, haltères devant les cuisses',
          'Levez devant vous',
          'Montez jusqu à hauteur épaules',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'rear_delt_fly',
        name: 'Oiseau pour Deltoïdes Arrière',
        description: 'Isolation de l arrière des épaules.',
        primaryMuscles: ['Épaules arrière'],
        secondaryMuscles: ['Trapèzes'],
        equipment: 'Haltères',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Buste penché en avant',
          'Haltères sous la poitrine',
          'Écartez les bras sur les côtés',
          'Contractez l arrière des épaules',
        ],
      ),
      Exercise(
        id: 'arnold_press',
        name: 'Développé Arnold',
        description: 'Variante créée par Arnold Schwarzenegger.',
        primaryMuscles: ['Épaules'],
        secondaryMuscles: ['Triceps'],
        equipment: 'Haltères',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Haltères devant les épaules, paumes vers soi',
          'Poussez en tournant les poignets',
          'Terminez paumes vers l avant',
          'Revenez en inversant le mouvement',
        ],
      ),
      Exercise(
        id: 'upright_row',
        name: 'Tirage Menton',
        description: 'Travaille épaules et trapèzes.',
        primaryMuscles: ['Épaules', 'Trapèzes'],
        secondaryMuscles: [],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Debout, barre devant les cuisses',
          'Tirez le long du corps',
          'Montez jusqu au menton',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'pike_push_up',
        name: 'Pompes Pike',
        description: 'Au poids du corps pour les épaules.',
        primaryMuscles: ['Épaules'],
        secondaryMuscles: ['Triceps'],
        equipment: 'Poids du corps',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Position V inversé',
          'Descendez la tête vers le sol',
          'Poussez pour remonter',
          'Gardez les jambes tendues',
        ],
      ),
      Exercise(
        id: 'handstand_push_up',
        name: 'Pompes Handstand',
        description: 'Exercice avancé au poids du corps.',
        primaryMuscles: ['Épaules'],
        secondaryMuscles: ['Triceps', 'Trapèzes'],
        equipment: 'Poids du corps',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'Position poirier contre un mur',
          'Descendez la tête vers le sol',
          'Poussez pour remonter',
          'Gardez le corps droit',
        ],
      ),
      Exercise(
        id: 'cable_lateral_raise',
        name: 'Élévations Latérales Câble',
        description: 'Tension continue sur les deltoïdes.',
        primaryMuscles: ['Épaules'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Debout de côté à une poulie basse',
          'Saisissez la poignée',
          'Levez le bras sur le côté',
          'Descendez lentement',
        ],
      ),
      Exercise(
        id: 'machine_shoulder_press',
        name: 'Développé Épaules Machine',
        description: 'Machine guidée pour les épaules.',
        primaryMuscles: ['Épaules'],
        secondaryMuscles: ['Triceps'],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Assis sur la machine',
          'Saisissez les poignées',
          'Poussez au-dessus de la tête',
          'Revenez contrôlé',
        ],
      ),
      Exercise(
        id: 'seated_dumbbell_press',
        name: 'Développé Assis Haltères',
        description: 'Développé épaules sur banc.',
        primaryMuscles: ['Épaules'],
        secondaryMuscles: ['Triceps'],
        equipment: 'Haltères',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Assis sur banc avec dossier',
          'Haltères aux épaules',
          'Poussez au-dessus de la tête',
          'Ramenez contrôlé',
        ],
      ),

      // ============ BICEPS (10 exercices) ============
      Exercise(
        id: 'barbell_curl',
        name: 'Curl Barre',
        description: 'Exercice de base pour les biceps.',
        primaryMuscles: ['Biceps'],
        secondaryMuscles: ['Avant-bras'],
        equipment: 'Barre',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Debout, barre en main',
          'Curl jusqu aux épaules',
          'Gardez les coudes fixes',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'dumbbell_curl',
        name: 'Curl Haltères',
        description: 'Travail alterné ou simultané.',
        primaryMuscles: ['Biceps'],
        secondaryMuscles: ['Avant-bras'],
        equipment: 'Haltères',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Debout, haltères en main',
          'Curl en alternance ou simultané',
          'Coudes le long du corps',
          'Descendez lentement',
        ],
      ),
      Exercise(
        id: 'hammer_curl',
        name: 'Curl Marteau',
        description: 'Cible les biceps et brachial.',
        primaryMuscles: ['Biceps', 'Avant-bras'],
        secondaryMuscles: [],
        equipment: 'Haltères',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Haltères en prise neutre',
          'Curl en gardant pouces vers le haut',
          'Coudes fixes',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'preacher_curl',
        name: 'Curl Pupitre',
        description: 'Isolation stricte des biceps.',
        primaryMuscles: ['Biceps'],
        secondaryMuscles: [],
        equipment: 'Barre',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Bras sur le pupitre',
          'Curl jusqu en haut',
          'Évitez de décoller les bras',
          'Descendez lentement',
        ],
      ),
      Exercise(
        id: 'concentration_curl',
        name: 'Curl Concentration',
        description: 'Focus unilatéral sur le biceps.',
        primaryMuscles: ['Biceps'],
        secondaryMuscles: [],
        equipment: 'Haltères',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Assis, coude contre l intérieur de la cuisse',
          'Curl vers l épaule',
          'Contraction maximale en haut',
          'Descendez lentement',
        ],
      ),
      Exercise(
        id: 'cable_curl',
        name: 'Curl Câble',
        description: 'Tension continue sur les biceps.',
        primaryMuscles: ['Biceps'],
        secondaryMuscles: ['Avant-bras'],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Debout face à la poulie',
          'Saisissez la barre',
          'Curl jusqu aux épaules',
          'Descendez en résistant',
        ],
      ),
      Exercise(
        id: 'incline_dumbbell_curl',
        name: 'Curl Incliné Haltères',
        description: 'Étirement maximal des biceps.',
        primaryMuscles: ['Biceps'],
        secondaryMuscles: [],
        equipment: 'Haltères',
        difficulty: 'Intermédiaire',
        category: 'Isolation',
        instructions: [
          'Allongé sur banc incliné',
          'Bras pendants',
          'Curl simultané ou alterné',
          'Descendez en étirant',
        ],
      ),
      Exercise(
        id: 'ez_bar_curl',
        name: 'Curl Barre EZ',
        description: 'Plus confortable pour les poignets.',
        primaryMuscles: ['Biceps'],
        secondaryMuscles: ['Avant-bras'],
        equipment: 'Barre',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Debout, barre EZ en main',
          'Curl jusqu aux épaules',
          'Coudes fixes',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'spider_curl',
        name: 'Curl Spider',
        description: 'Isolation stricte, focus pic du biceps.',
        primaryMuscles: ['Biceps'],
        secondaryMuscles: [],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Isolation',
        instructions: [
          'Allongé ventre sur banc incliné',
          'Bras pendants devant',
          'Curl vers le haut',
          'Descendez lentement',
        ],
      ),
      Exercise(
        id: 'reverse_curl',
        name: 'Curl Inversé',
        description: 'Cible les avant-bras et brachial.',
        primaryMuscles: ['Avant-bras'],
        secondaryMuscles: ['Biceps'],
        equipment: 'Barre',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Prise pronation (paumes vers le bas)',
          'Curl jusqu aux épaules',
          'Coudes fixes',
          'Descendez contrôlé',
        ],
      ),

      // ============ TRICEPS (10 exercices) ============
      Exercise(
        id: 'close_grip_bench',
        name: 'Développé Serré',
        description: 'Exercice de base pour les triceps.',
        primaryMuscles: ['Triceps'],
        secondaryMuscles: ['Pectoraux', 'Épaules'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Allongé sur banc',
          'Prise serrée sur la barre',
          'Descendez vers la poitrine',
          'Poussez en gardant coudes près du corps',
        ],
      ),
      Exercise(
        id: 'tricep_dips',
        name: 'Dips Triceps',
        description: 'Excellent exercice au poids du corps.',
        primaryMuscles: ['Triceps'],
        secondaryMuscles: ['Pectoraux', 'Épaules'],
        equipment: 'Barres parallèles',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Corps droit entre les barres',
          'Descendez en fléchissant les coudes',
          'Gardez le corps vertical',
          'Poussez pour remonter',
        ],
      ),
      Exercise(
        id: 'overhead_tricep_extension',
        name: 'Extension Triceps au-dessus de la tête',
        description: 'Étirement profond des triceps.',
        primaryMuscles: ['Triceps'],
        secondaryMuscles: [],
        equipment: 'Haltères',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Debout, haltère au-dessus de la tête',
          'Descendez derrière la tête',
          'Gardez les coudes fixes',
          'Poussez vers le haut',
        ],
      ),
      Exercise(
        id: 'tricep_pushdown',
        name: 'Pushdown Triceps',
        description: 'Isolation des triceps à la poulie.',
        primaryMuscles: ['Triceps'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Debout face à la poulie haute',
          'Coudes le long du corps',
          'Poussez vers le bas',
          'Remontez contrôlé',
        ],
      ),
      Exercise(
        id: 'skull_crusher',
        name: 'Barre au Front',
        description: 'Isolation intensive des triceps.',
        primaryMuscles: ['Triceps'],
        secondaryMuscles: [],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Isolation',
        instructions: [
          'Allongé sur banc, barre au-dessus',
          'Descendez vers le front',
          'Coudes fixes',
          'Poussez vers le haut',
        ],
      ),
      Exercise(
        id: 'kickback',
        name: 'Kickback Triceps',
        description: 'Isolation unilatérale des triceps.',
        primaryMuscles: ['Triceps'],
        secondaryMuscles: [],
        equipment: 'Haltères',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Buste penché, coude plié',
          'Tendez le bras vers l arrière',
          'Contractez en haut',
          'Revenez contrôlé',
        ],
      ),
      Exercise(
        id: 'bench_dips',
        name: 'Dips sur Banc',
        description: 'Version simplifiée des dips.',
        primaryMuscles: ['Triceps'],
        secondaryMuscles: ['Épaules'],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Mains sur un banc derrière vous',
          'Jambes tendues ou pliées',
          'Descendez en fléchissant les coudes',
          'Poussez pour remonter',
        ],
      ),
      Exercise(
        id: 'rope_pushdown',
        name: 'Pushdown à la Corde',
        description: 'Permet une contraction maximale.',
        primaryMuscles: ['Triceps'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Poulie haute avec corde',
          'Poussez en écartant les extrémités',
          'Contractez en bas',
          'Remontez contrôlé',
        ],
      ),
      Exercise(
        id: 'close_push_up',
        name: 'Pompes Serrées',
        description: 'Variante au poids du corps.',
        primaryMuscles: ['Triceps'],
        secondaryMuscles: ['Pectoraux'],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Position pompe, mains rapprochées',
          'Descendez en gardant coudes près du corps',
          'Poussez pour remonter',
          'Répétez',
        ],
      ),
      Exercise(
        id: 'cable_overhead_extension',
        name: 'Extension Overhead Câble',
        description: 'Tension continue sur les triceps.',
        primaryMuscles: ['Triceps'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Dos à la poulie basse',
          'Corde au-dessus de la tête',
          'Tendez les bras vers l avant',
          'Revenez contrôlé',
        ],
      ),

      // ============ JAMBES - QUADRICEPS (12 exercices) ============
      Exercise(
        id: 'squat',
        name: 'Squat Barre',
        description: 'Roi des exercices pour les jambes.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: ['Fessiers', 'Ischio-jambiers', 'Lombaires'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Barre sur les épaules',
          'Pieds largeur épaules',
          'Descendez en fléchissant genoux et hanches',
          'Remontez en poussant sur les talons',
        ],
      ),
      Exercise(
        id: 'front_squat',
        name: 'Squat Avant',
        description: 'Cible davantage les quadriceps.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: ['Fessiers', 'Lombaires'],
        equipment: 'Barre',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'Barre sur l avant des épaules',
          'Coudes hauts',
          'Descendez en gardant le buste droit',
          'Remontez',
        ],
      ),
      Exercise(
        id: 'leg_press',
        name: 'Presse à Cuisses',
        description: 'Machine pour travailler les cuisses.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: ['Fessiers', 'Ischio-jambiers'],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Assis sur la machine',
          'Pieds sur la plateforme',
          'Poussez en tendant les jambes',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'leg_extension',
        name: 'Extension de Jambes',
        description: 'Isolation des quadriceps.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Assis sur la machine',
          'Tendez les jambes',
          'Contractez en haut',
          'Descendez lentement',
        ],
      ),
      Exercise(
        id: 'bulgarian_split_squat',
        name: 'Squat Bulgare',
        description: 'Travail unilatéral des jambes.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: ['Fessiers'],
        equipment: 'Haltères',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Pied arrière surélevé sur un banc',
          'Descendez sur la jambe avant',
          'Remontez',
          'Alternez les jambes',
        ],
      ),
      Exercise(
        id: 'goblet_squat',
        name: 'Goblet Squat',
        description: 'Squat avec haltère ou kettlebell.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: ['Fessiers'],
        equipment: 'Haltères',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Haltère contre la poitrine',
          'Descendez en squat',
          'Gardez le buste droit',
          'Remontez',
        ],
      ),
      Exercise(
        id: 'lunge',
        name: 'Fentes',
        description: 'Exercice complet pour les jambes.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: ['Fessiers', 'Ischio-jambiers'],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Pas en avant',
          'Descendez jusqu à ce que le genou touche presque le sol',
          'Remontez',
          'Alternez les jambes',
        ],
      ),
      Exercise(
        id: 'walking_lunge',
        name: 'Fentes Marchées',
        description: 'Variante dynamique des fentes.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: ['Fessiers'],
        equipment: 'Haltères',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Haltères dans chaque main',
          'Pas en avant et descendez',
          'Remontez et avancez',
          'Continuez à marcher',
        ],
      ),
      Exercise(
        id: 'hack_squat',
        name: 'Hack Squat',
        description: 'Machine pour les quadriceps.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: ['Fessiers'],
        equipment: 'Machine',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Dos contre le support',
          'Pieds sur la plateforme',
          'Descendez en fléchissant les genoux',
          'Poussez pour remonter',
        ],
      ),
      Exercise(
        id: 'sissy_squat',
        name: 'Sissy Squat',
        description: 'Isolation intensive des quadriceps.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: [],
        equipment: 'Poids du corps',
        difficulty: 'Avancé',
        category: 'Isolation',
        instructions: [
          'Debout, talons surélevés',
          'Penchez en arrière en fléchissant les genoux',
          'Descendez jusqu au sol',
          'Remontez',
        ],
      ),
      Exercise(
        id: 'box_squat',
        name: 'Box Squat',
        description: 'Squat sur boîte.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: ['Fessiers', 'Ischio-jambiers'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Barre sur les épaules',
          'Boîte derrière vous',
          'Descendez jusqu à toucher la boîte',
          'Remontez explosif',
        ],
      ),
      Exercise(
        id: 'pistol_squat',
        name: 'Pistol Squat',
        description: 'Squat sur une jambe.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: ['Fessiers'],
        equipment: 'Poids du corps',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'Équilibre sur une jambe',
          'Descendez en squat',
          'Jambe libre tendue devant',
          'Remontez',
        ],
      ),

      // ============ JAMBES - ISCHIO-JAMBIERS (8 exercices) ============
      Exercise(
        id: 'romanian_deadlift',
        name: 'Soulevé de Terre Roumain',
        description: 'Excellente pour les ischio-jambiers.',
        primaryMuscles: ['Ischio-jambiers'],
        secondaryMuscles: ['Fessiers', 'Lombaires'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Barre en main, jambes légèrement fléchies',
          'Penchez en avant depuis les hanches',
          'Descendez la barre le long des jambes',
          'Remontez en contractant les ischios',
        ],
      ),
      Exercise(
        id: 'leg_curl',
        name: 'Leg Curl',
        description: 'Isolation des ischio-jambiers.',
        primaryMuscles: ['Ischio-jambiers'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Allongé sur la machine',
          'Fléchissez les jambes',
          'Amenez les talons vers les fesses',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'nordic_curl',
        name: 'Nordic Curl',
        description: 'Exercice excentrique intense.',
        primaryMuscles: ['Ischio-jambiers'],
        secondaryMuscles: [],
        equipment: 'Poids du corps',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'Genoux au sol, chevilles maintenues',
          'Penchez le corps vers l avant',
          'Résistez avec les ischios',
          'Poussez pour remonter',
        ],
      ),
      Exercise(
        id: 'glute_ham_raise',
        name: 'Glute Ham Raise',
        description: 'Machine pour ischios et fessiers.',
        primaryMuscles: ['Ischio-jambiers'],
        secondaryMuscles: ['Fessiers'],
        equipment: 'Machine',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'Sur la machine GHR',
          'Descendez le buste vers le sol',
          'Remontez en contractant les ischios',
          'Répétez',
        ],
      ),
      Exercise(
        id: 'stiff_leg_deadlift',
        name: 'Soulevé Jambes Tendues',
        description: 'Variante ciblant les ischios.',
        primaryMuscles: ['Ischio-jambiers'],
        secondaryMuscles: ['Lombaires'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Jambes presque tendues',
          'Penchez en avant depuis les hanches',
          'Descendez la barre au sol',
          'Remontez',
        ],
      ),
      Exercise(
        id: 'single_leg_rdl',
        name: 'RDL Unilatéral',
        description: 'Travail d équilibre et ischios.',
        primaryMuscles: ['Ischio-jambiers'],
        secondaryMuscles: ['Fessiers'],
        equipment: 'Haltères',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Équilibre sur une jambe',
          'Penchez en avant',
          'Jambe libre tendue derrière',
          'Remontez',
        ],
      ),
      Exercise(
        id: 'good_morning',
        name: 'Good Morning',
        description: 'Exercice pour ischios et lombaires.',
        primaryMuscles: ['Ischio-jambiers', 'Lombaires'],
        secondaryMuscles: [],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Barre sur les épaules',
          'Penchez en avant depuis les hanches',
          'Gardez le dos droit',
          'Remontez',
        ],
      ),
      Exercise(
        id: 'seated_leg_curl',
        name: 'Leg Curl Assis',
        description: 'Variante assise du leg curl.',
        primaryMuscles: ['Ischio-jambiers'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Assis sur la machine',
          'Fléchissez les jambes vers le bas',
          'Contractez en bas',
          'Remontez lentement',
        ],
      ),

      // ============ FESSIERS (8 exercices) ============
      Exercise(
        id: 'hip_thrust',
        name: 'Hip Thrust',
        description: 'Exercice roi pour les fessiers.',
        primaryMuscles: ['Fessiers'],
        secondaryMuscles: ['Ischio-jambiers'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Dos contre un banc, barre sur les hanches',
          'Poussez les hanches vers le haut',
          'Contractez les fessiers en haut',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'glute_bridge',
        name: 'Pont Fessier',
        description: 'Variante au sol du hip thrust.',
        primaryMuscles: ['Fessiers'],
        secondaryMuscles: ['Ischio-jambiers'],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Allongé au sol, genoux fléchis',
          'Soulevez les hanches',
          'Contractez en haut',
          'Descendez',
        ],
      ),
      Exercise(
        id: 'cable_kickback',
        name: 'Kickback Câble',
        description: 'Isolation des fessiers.',
        primaryMuscles: ['Fessiers'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Face à la poulie basse',
          'Manchette à la cheville',
          'Poussez la jambe vers l arrière',
          'Contractez le fessier',
        ],
      ),
      Exercise(
        id: 'step_up',
        name: 'Step Up',
        description: 'Montée sur boîte.',
        primaryMuscles: ['Quadriceps', 'Fessiers'],
        secondaryMuscles: [],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Montez sur une boîte',
          'Poussez avec la jambe avant',
          'Descendez contrôlé',
          'Alternez les jambes',
        ],
      ),
      Exercise(
        id: 'sumo_deadlift',
        name: 'Soulevé Sumo',
        description: 'Variante large ciblant les fessiers.',
        primaryMuscles: ['Fessiers', 'Ischio-jambiers'],
        secondaryMuscles: ['Quadriceps', 'Lombaires'],
        equipment: 'Barre',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Stance large, orteils vers l extérieur',
          'Saisissez la barre',
          'Soulevez en poussant sur les talons',
          'Verrouillez en haut',
        ],
      ),
      Exercise(
        id: 'fire_hydrant',
        name: 'Fire Hydrant',
        description: 'Isolation du moyen fessier.',
        primaryMuscles: ['Fessiers'],
        secondaryMuscles: [],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'À quatre pattes',
          'Levez la jambe sur le côté',
          'Gardez le genou plié',
          'Revenez',
        ],
      ),
      Exercise(
        id: 'donkey_kick',
        name: 'Donkey Kick',
        description: 'Activation des fessiers.',
        primaryMuscles: ['Fessiers'],
        secondaryMuscles: [],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'À quatre pattes',
          'Poussez une jambe vers le haut',
          'Pied flex, talon vers le plafond',
          'Contractez le fessier',
        ],
      ),
      Exercise(
        id: 'abduction_machine',
        name: 'Machine Abduction',
        description: 'Machine pour le moyen fessier.',
        primaryMuscles: ['Fessiers'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Assis sur la machine',
          'Écartez les jambes',
          'Contractez les fessiers',
          'Revenez lentement',
        ],
      ),

      // ============ MOLLETS (5 exercices) ============
      Exercise(
        id: 'standing_calf_raise',
        name: 'Mollets Debout',
        description: 'Exercice de base pour les mollets.',
        primaryMuscles: ['Mollets'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Debout sur la machine',
          'Montez sur la pointe des pieds',
          'Contractez en haut',
          'Descendez en étirant',
        ],
      ),
      Exercise(
        id: 'seated_calf_raise',
        name: 'Mollets Assis',
        description: 'Cible le soléaire.',
        primaryMuscles: ['Mollets'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Assis sur la machine',
          'Pointes des pieds sur le support',
          'Montez sur la pointe',
          'Descendez en étirant',
        ],
      ),
      Exercise(
        id: 'jump_rope',
        name: 'Corde à Sauter',
        description: 'Cardio et travail des mollets.',
        primaryMuscles: ['Mollets'],
        secondaryMuscles: [],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Cardio',
        instructions: [
          'Sautez à la corde',
          'Rebondissez sur la pointe des pieds',
          'Restez sur les avant-pieds',
          'Variez la vitesse',
        ],
      ),
      Exercise(
        id: 'donkey_calf_raise',
        name: 'Mollets Donkey',
        description: 'Étirement maximal des mollets.',
        primaryMuscles: ['Mollets'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Intermédiaire',
        category: 'Isolation',
        instructions: [
          'Buste penché, charge sur le bas du dos',
          'Montez sur la pointe',
          'Contractez en haut',
          'Descendez en étirant',
        ],
      ),
      Exercise(
        id: 'single_leg_calf_raise',
        name: 'Mollets Unilatéral',
        description: 'Une jambe à la fois.',
        primaryMuscles: ['Mollets'],
        secondaryMuscles: [],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Isolation',
        instructions: [
          'Debout sur une jambe',
          'Montez sur la pointe',
          'Contractez',
          'Descendez et répétez',
        ],
      ),

      // ============ ABDOMINAUX (10 exercices) ============
      Exercise(
        id: 'crunch',
        name: 'Crunch',
        description: 'Exercice de base pour les abdos.',
        primaryMuscles: ['Abdominaux'],
        secondaryMuscles: [],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Allongé au sol, genoux fléchis',
          'Relevez les épaules du sol',
          'Contractez les abdos',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'plank',
        name: 'Planche',
        description: 'Gainage isométrique.',
        primaryMuscles: ['Abdominaux'],
        secondaryMuscles: ['Lombaires'],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Coudes au sol, corps droit',
          'Contractez les abdos',
          'Maintenez la position',
          'Respirez normalement',
        ],
      ),
      Exercise(
        id: 'russian_twist',
        name: 'Russian Twist',
        description: 'Travail des obliques.',
        primaryMuscles: ['Abdominaux', 'Obliques'],
        secondaryMuscles: [],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Assis, pieds surélevés',
          'Tournez le buste d un côté à l autre',
          'Contractez les obliques',
          'Gardez le dos droit',
        ],
      ),
      Exercise(
        id: 'leg_raise',
        name: 'Relevé de Jambes',
        description: 'Cible le bas des abdos.',
        primaryMuscles: ['Abdominaux'],
        secondaryMuscles: [],
        equipment: 'Poids du corps',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Allongé au sol',
          'Levez les jambes tendues',
          'Montez jusqu à 90 degrés',
          'Descendez sans toucher le sol',
        ],
      ),
      Exercise(
        id: 'bicycle_crunch',
        name: 'Crunch Vélo',
        description: 'Travail dynamique des abdos.',
        primaryMuscles: ['Abdominaux', 'Obliques'],
        secondaryMuscles: [],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Allongé, mains derrière la tête',
          'Amenez coude et genou opposés',
          'Alternez rapidement',
          'Gardez le dos au sol',
        ],
      ),
      Exercise(
        id: 'mountain_climber',
        name: 'Mountain Climber',
        description: 'Cardio et abdos.',
        primaryMuscles: ['Abdominaux'],
        secondaryMuscles: [],
        equipment: 'Poids du corps',
        difficulty: 'Intermédiaire',
        category: 'Cardio',
        instructions: [
          'Position de planche',
          'Amenez les genoux vers la poitrine',
          'Alternez rapidement',
          'Gardez les hanches basses',
        ],
      ),
      Exercise(
        id: 'hanging_leg_raise',
        name: 'Relevé de Jambes Suspendu',
        description: 'Version avancée des relevés de jambes.',
        primaryMuscles: ['Abdominaux'],
        secondaryMuscles: [],
        equipment: 'Barre de traction',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'Suspendu à une barre',
          'Levez les jambes tendues',
          'Montez jusqu à l horizontale',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'ab_wheel',
        name: 'Roue Abdominale',
        description: 'Exercice très intensif.',
        primaryMuscles: ['Abdominaux'],
        secondaryMuscles: ['Lombaires'],
        equipment: 'Poids du corps',
        difficulty: 'Avancé',
        category: 'Force',
        instructions: [
          'À genoux, roue en main',
          'Roulez vers l avant',
          'Allez le plus loin possible',
          'Revenez en contractant les abdos',
        ],
      ),
      Exercise(
        id: 'cable_crunch',
        name: 'Crunch Câble',
        description: 'Crunch avec résistance.',
        primaryMuscles: ['Abdominaux'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'À genoux face à la poulie',
          'Corde derrière la tête',
          'Descendez en contractant les abdos',
          'Remontez contrôlé',
        ],
      ),
      Exercise(
        id: 'side_plank',
        name: 'Planche Latérale',
        description: 'Gainage des obliques.',
        primaryMuscles: ['Obliques'],
        secondaryMuscles: ['Abdominaux'],
        equipment: 'Poids du corps',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Sur le côté, appui sur le coude',
          'Corps aligné',
          'Maintenez la position',
          'Changez de côté',
        ],
      ),

      // ============ LOMBAIRES (5 exercices) ============
      Exercise(
        id: 'back_extension',
        name: 'Extension Lombaires',
        description: 'Renforcement du bas du dos.',
        primaryMuscles: ['Lombaires'],
        secondaryMuscles: ['Fessiers'],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Sur banc à lombaires',
          'Descendez le buste',
          'Remontez en contractant le bas du dos',
          'Répétez',
        ],
      ),
      Exercise(
        id: 'superman',
        name: 'Superman',
        description: 'Exercice au sol pour le dos.',
        primaryMuscles: ['Lombaires'],
        secondaryMuscles: [],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'Allongé ventre au sol',
          'Levez bras et jambes simultanément',
          'Contractez le dos',
          'Maintenez 2-3 secondes',
        ],
      ),
      Exercise(
        id: 'reverse_hyper',
        name: 'Reverse Hyperextension',
        description: 'Machine pour lombaires et fessiers.',
        primaryMuscles: ['Lombaires', 'Fessiers'],
        secondaryMuscles: [],
        equipment: 'Machine',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Allongé ventre sur la machine',
          'Levez les jambes vers l arrière',
          'Contractez lombaires et fessiers',
          'Descendez contrôlé',
        ],
      ),
      Exercise(
        id: 'bird_dog',
        name: 'Bird Dog',
        description: 'Exercice d équilibre pour le dos.',
        primaryMuscles: ['Lombaires'],
        secondaryMuscles: ['Abdominaux'],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Force',
        instructions: [
          'À quatre pattes',
          'Tendez bras et jambe opposés',
          'Maintenez l équilibre',
          'Alternez',
        ],
      ),
      Exercise(
        id: 'weighted_back_extension',
        name: 'Extension Lombaires Lesté',
        description: 'Variante avec charge.',
        primaryMuscles: ['Lombaires'],
        secondaryMuscles: ['Fessiers'],
        equipment: 'Haltères',
        difficulty: 'Intermédiaire',
        category: 'Force',
        instructions: [
          'Sur banc à lombaires',
          'Disque contre la poitrine',
          'Descendez et remontez',
          'Contractez en haut',
        ],
      ),

      // ============ CARDIO (5 exercices) ============
      Exercise(
        id: 'burpee',
        name: 'Burpee',
        description: 'Exercice complet haute intensité.',
        primaryMuscles: ['Abdominaux'],
        secondaryMuscles: ['Pectoraux', 'Épaules', 'Quadriceps'],
        equipment: 'Poids du corps',
        difficulty: 'Intermédiaire',
        category: 'Cardio',
        instructions: [
          'Commencez debout',
          'Descendez en squat',
          'Position planche',
          'Pompe',
          'Sautez en position squat',
          'Sautez en l air',
        ],
      ),
      Exercise(
        id: 'box_jump',
        name: 'Saut sur Boîte',
        description: 'Explosivité des jambes.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: ['Fessiers', 'Mollets'],
        equipment: 'Poids du corps',
        difficulty: 'Intermédiaire',
        category: 'Pliométrique',
        instructions: [
          'Face à une boîte',
          'Sautez dessus',
          'Atterrissez doucement',
          'Descendez et répétez',
        ],
      ),
      Exercise(
        id: 'high_knees',
        name: 'Montées de Genoux',
        description: 'Cardio sur place.',
        primaryMuscles: ['Quadriceps'],
        secondaryMuscles: ['Mollets'],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Cardio',
        instructions: [
          'Sur place',
          'Montez les genoux haut',
          'Alternez rapidement',
          'Gardez le rythme',
        ],
      ),
      Exercise(
        id: 'jumping_jack',
        name: 'Jumping Jack',
        description: 'Échauffement et cardio.',
        primaryMuscles: ['Épaules'],
        secondaryMuscles: ['Mollets'],
        equipment: 'Poids du corps',
        difficulty: 'Débutant',
        category: 'Cardio',
        instructions: [
          'Sautez en écartant bras et jambes',
          'Revenez en position de départ',
          'Répétez rapidement',
          'Restez sur la pointe des pieds',
        ],
      ),
      Exercise(
        id: 'battle_ropes',
        name: 'Battle Ropes',
        description: 'Cardio intense avec cordes.',
        primaryMuscles: ['Épaules'],
        secondaryMuscles: ['Abdominaux', 'Avant-bras'],
        equipment: 'Poids du corps',
        difficulty: 'Intermédiaire',
        category: 'Cardio',
        instructions: [
          'Saisissez les cordes',
          'Fouettez de haut en bas',
          'Alternez ou simultané',
          'Maintenez l intensité',
        ],
      ),
    ];
  }
}
