// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAAzixaXefVjGUJeul6QOTIM99PCDfdPM',
    appId: '1:337498862004:web:placeholder',
    messagingSenderId: '337498862004',
    projectId: 'muscle-master-48827',
    authDomain: 'muscle-master-48827.firebaseapp.com',
    storageBucket: 'muscle-master-48827.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAAzixaXefVjGUJeul6QOTIM99PCDfdPM',
    appId: '1:337498862004:android:733cd93a84ad63df7e42e1',
    messagingSenderId: '337498862004',
    projectId: 'muscle-master-48827',
    storageBucket: 'muscle-master-48827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAAzixaXefVjGUJeul6QOTIM99PCDfdPM',
    appId: '1:337498862004:ios:placeholder',
    messagingSenderId: '337498862004',
    projectId: 'muscle-master-48827',
    storageBucket: 'muscle-master-48827.firebasestorage.app',
    iosBundleId: 'com.musclemaster.fitness',
  );
}
